
const data = {
 
  products: [
    {
      name: 'Black Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kpmy8i80/shirt/9/t/o/l-srt-001-black-foxter-original-imag3tgmehh6e2gy.jpeg?q=50',
      price: 90,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular black shirt',
    },
    {
      name: 'Free Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kfu0h3k0-0/shirt/d/a/l/40-assfqmofl98913-allen-solly-original-imafw6v9p9mzrmzz.jpeg?q=50',
      price: 70,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kjiwfbk0-0/t-shirt/e/k/s/m-t305-as10yldnwh-seven-rocks-original-imafz2qfvx7tznnn.jpeg?q=50',
      price: 60,
      rating: 4.2,
      numReviews: 15,
      countInStock: 30,
      description: 'A popular fit shirt',
    },
    {
      name: 'Green Black Dress',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kbgu1e80/kurta/t/2/p/s-wt002black-women-touch-original-imafstgpcq5fqg92.jpeg?q=50',
      price:90,
      rating: 4.0,
      numReviews: 15,
      countInStock: 30,
      description: 'A Green Black Dress',
    },
    {
      name:'kids dress one',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/k5r2mq80/kids-ethnic-set/d/z/5/9-10-years-40581-smartraho-original-imafkhautaku3ebr.jpeg?q=50',
      price:40,
      rating: 3.5,
      numReviews: 25,
      countInStock: 30,
      description: 'kids best dress one',
    },
    {
      name: 'A top for girls ',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kuipea80/top/h/5/o/l-top-d3-brucella-original-imag7mbksgrkywbk.jpeg?q=50',
      price:75,
      rating: 4.2,
      numReviews: 15,
      countInStock: 30,
      description: 'girls nice  top',
    },
    {
      name:'kids dress two',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/k5r2mq80/kids-ethnic-set/d/z/5/9-10-years-40581-smartraho-original-imafkhautaku3ebr.jpeg?q=50',
      price:80,
      rating: 3.5,
      numReviews: 25,
      countInStock: 30,
      description: 'kids best dress two',
    },
    {
      name: 'girls best top',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kdukgi80/top/m/k/m/s-kk104mh-kipek-original-imafuz42ywnzuruq.jpeg?q=50',
      price:100,
      rating: 4.0,
      numReviews: 15,
      countInStock: 30,
      description: 'girls nice  top',
    },
    {
      name:'Blue dress for kids',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/kij6f0w0/kids-ethnic-set/j/j/d/2-3-years-4040-smartraho-original-imafyaz2hepm2zry.jpeg?q=50',
      price:90,
      rating: 3.5,
      numReviews: 25,
      countInStock: 30,
      description: 'Blue kids best dress one',
    },
    {
      name: 'colored kurti',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/k1tm1e80/fabric/g/r/z/899d197-852d158-saara-original-imafkfcwqhpkdmmg.jpeg?q=50',
      price:80,
      rating: 4.5,
      numReviews: 45,
      countInStock: 30,
      description: 'girls colored kurti',
    },
    {
      name: 'best colored Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/ktrk13k0/shirt/s/8/t/40-lysfcslpc49901-louis-philippe-sport-original-imag7f4mnwz9tcby.jpeg?q=50',
      price: 70,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular colored shirt',
    },
    {
      name: 'best fit colored Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kf1fo280hlty2aw-0/t-shirt/p/9/v/-original-imafey9yzuqh7d5h.jpeg?q=50',
      price: 96,
      rating: 2.5,
      numReviews: 18,
      countInStock: 40,
      description: 'A popular fit colored shirt',
    },
    {
      name: 'Top colored Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kd94uq80/t-shirt/k/2/j/m-mss20cn029a-metronaut-original-imafu7buaeudks8h.jpeg?q=50',
      price: 72,
      rating: 3.5,
      numReviews: 17,
      countInStock: 29,
      description: 'A Top colored shirt',
    },
    {
      name: 'Black Shirt for women',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/jr0y9ow0/shirt/b/t/w/xl-funfas-0001-funday-fashion-original-imafcwzzmfh8mvx8.jpeg?q=50',
      price:90,
      rating: 4.3,
      numReviews: 25,
      countInStock: 35,
      description: 'best Black Shirt for women',
    },
    {
      name: 'Grey Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kc0u7bk0/shirt/k/a/a/m-pk19sh09g-surhi-original-imaft8vgvhmhbhsy.jpeg?q=50',
      price: 93,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular grey shirt',
    },
    {
      name: 'Red Shirt',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kim1aq80-0/shirt/k/n/i/l-skcsh-1106-mao-fubar-original-imafycz5hpfmhhyp.jpeg?q=50',
      price: 85,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular red shirt',
    },
    {
      name: 'Red Top',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/jrkyfm80/top/v/c/d/xl-vtntop-04-vaanya-original-imafdcpbmrf6y7p6.jpeg?q=50',
      price: 87,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular red top',
    },
    {
      name: 'Black Top',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/knni7ww0/top/9/f/u/xxl-dmp299-dmp-fashion-original-imag2a5qpy986cmy.jpeg?q=50',
      price: 95,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular Black top',
    },
    {
      name: 'Yellow Dress',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/k226oi80/kids-dress/g/a/m/10-11-years-dezine-mustard-yellow-and-black-koli-kaarigari-original-imafhgvp9afnsmta.jpeg?q=50',
      price: 91,
      rating: 4.5,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular Yellow dress',
    },
    {
      name: 'Pink Dress',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/kfoapow0/kids-t-shirt/u/h/b/4-5-years-f-40886-smartraho-original-imafw284vzcywhxf.jpeg?q=50',
      price: 69,
      rating: 4.5,
      numReviews: 40,
      countInStock: 20,
      description: 'A popular Pink dress',
    },
    {
      name: 'Green Dress',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/kvba7bk0/sweatshirt/q/s/b/3-4-years-521053102-2-monte-carlo-original-imag88uymekgydck.jpeg?q=50',
      price: 55,
      rating: 4.5,
      numReviews: 40,
      countInStock: 20,
      description: 'A popular Green dress',
    },
    {
      name: 'White Blue Dress',
      category: 'kids',
      image: 'https://rukminim1.flixcart.com/image/580/696/kv9urgw0/sweatshirt/p/a/p/5-6-years-mcbaw21ss029c-miss-chief-original-imag87nsq6mvxebx.jpeg?q=50',
      price: 73,
      rating: 4.2,
      numReviews: 30,
      countInStock: 20,
      description: 'A popular White Blue dress',
    },
    {
      name: 'Checked shari',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kn97te80/sari/l/d/n/free-1068-k-shaibo-saree-unstitched-original-imagfz7jpaquwduy.jpeg?q=50',
      price: 105,
      rating: 4.5,
      numReviews: 40,
      countInStock: 20,
      description: 'A popular Checked shari',
    },
    {
      name: 'Yellow Kurti',
      category: 'womens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kg8avm80-0/kurta/8/v/8/xl-ku233-mahageeta-original-imafwgc6qeatcjay.jpeg?q=50',
      price: 88,
      rating: 3.5,
      numReviews: 45,
      countInStock: 20,
      description: 'A popular Yellow kurti',
    },
    {
      name: 'White mens dress',
      category: 'mens',
      image: 'https://rukminim1.flixcart.com/image/580/696/kpsnzww0/shirt/5/6/r/s-gg370-gespo-original-imag3y46xefp2zu3.jpeg?q=50',
      price: 75,
      rating: 4.5,
      numReviews: 40,
      countInStock: 20,
      description: 'A popular White mens dress',
    },
  ],
};
export default data;
